# Generated by Django 3.1.2 on 2020-10-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Finance', 'Finance'), ('HR', 'HR'), ('Buildings', 'Buildings'), ('Clinical', 'Clinical')], default='Default', max_length=254)),
                ('owner', models.CharField(choices=[('Nikki', 'Nikki'), ('Simon', 'Simon'), ('Mani', 'Mani'), ('Susan', 'Susan')], default='Default', max_length=254)),
                ('action', models.TextField(default='', max_length=254)),
                ('closed', models.BooleanField(default=False)),
                ('date_complete', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('Feburary', 'Feburary'), ('September', 'September'), ('October', 'October')], default='Default', max_length=254)),
                ('income', models.IntegerField()),
                ('Expenditure', models.IntegerField()),
                ('Payroll', models.DecimalField(decimal_places=2, max_digits=6)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actual', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('Feburary', 'Feburary'), ('September', 'September'), ('October', 'October')], default='Default', max_length=254)),
                ('clinical', models.IntegerField()),
                ('admin', models.IntegerField()),
                ('headcount', models.IntegerField()),
                ('sickdays', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(default='', max_length=254)),
                ('area', models.CharField(choices=[('Finance', 'Finance'), ('HR', 'HR'), ('Buildings', 'Buildings'), ('Clinical', 'Clinical')], default='default', max_length=254)),
                ('closed', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Finance', 'Finance'), ('HR', 'HR'), ('Buildings', 'Buildings'), ('Clinical', 'Clinical')], default='Default', max_length=254)),
                ('owner', models.CharField(choices=[('Nikki', 'Nikki'), ('Simon', 'Simon'), ('Mani', 'Mani'), ('Susan', 'Susan')], default='Default', max_length=254)),
                ('risk', models.TextField(default='', max_length=254)),
                ('control', models.TextField(default='', max_length=254)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='Default', max_length=254)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
    ]
