# Generated by Django 3.1.2 on 2020-10-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Finance', 'Finance'), ('HR', 'HR'), ('Buildings', 'Buildings'), ('Clinical', 'Clinical')], default='Default', max_length=254)),
                ('rag', models.CharField(choices=[('Red', 'Red'), ('Amber', 'Amber'), ('Green', 'Green')], default='Green', max_length=254)),
            ],
        ),
    ]
