# Generated by Django 3.1.2 on 2020-10-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rag'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='owner',
            field=models.CharField(choices=[('Nikki', 'Nikki'), ('Simon', 'Simon'), ('Mani', 'Mani'), ('Susan', 'Susan')], default='Default', max_length=254),
        ),
    ]
