# Generated by Django 3.1.2 on 2020-11-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_issue_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='owner',
            field=models.CharField(choices=[('Nikki', 'Nikki'), ('Simon', 'Simon'), ('Mani', 'Mani'), ('Susan', 'Susan'), ('Rebecca', 'Rebecca'), ('Caroline', 'Caroline'), ('Mike', 'Mike')], default='Default', max_length=254),
        ),
        migrations.AlterField(
            model_name='issue',
            name='owner',
            field=models.CharField(choices=[('Nikki', 'Nikki'), ('Simon', 'Simon'), ('Mani', 'Mani'), ('Susan', 'Susan'), ('Rebecca', 'Rebecca'), ('Caroline', 'Caroline'), ('Mike', 'Mike')], default='Default', max_length=254),
        ),
        migrations.AlterField(
            model_name='risk',
            name='owner',
            field=models.CharField(choices=[('Nikki', 'Nikki'), ('Simon', 'Simon'), ('Mani', 'Mani'), ('Susan', 'Susan'), ('Rebecca', 'Rebecca'), ('Caroline', 'Caroline'), ('Mike', 'Mike')], default='Default', max_length=254),
        ),
    ]
