# Generated by Django 3.1.2 on 2020-11-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20201103_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='risk',
            name='control',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk',
            field=models.TextField(default='', max_length=600),
        ),
    ]
