# Generated by Django 3.1.2 on 2020-11-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20201103_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='owner',
            field=models.CharField(choices=[('Nikki', 'Nikki'), ('Simon', 'Simon'), ('Mani', 'Mani'), ('Susan', 'Susan'), ('Rebecca', 'Rebecca'), ('Caroline', 'Caroline'), ('Mike', 'Mike'), ('Suzy', 'Suzy'), ('Partners', 'Partners')], default='Default', max_length=254),
        ),
        migrations.AlterField(
            model_name='issue',
            name='owner',
            field=models.CharField(choices=[('Nikki', 'Nikki'), ('Simon', 'Simon'), ('Mani', 'Mani'), ('Susan', 'Susan'), ('Rebecca', 'Rebecca'), ('Caroline', 'Caroline'), ('Mike', 'Mike'), ('Suzy', 'Suzy'), ('Partners', 'Partners')], default='Default', max_length=254),
        ),
        migrations.AlterField(
            model_name='risk',
            name='owner',
            field=models.CharField(choices=[('Nikki', 'Nikki'), ('Simon', 'Simon'), ('Mani', 'Mani'), ('Susan', 'Susan'), ('Rebecca', 'Rebecca'), ('Caroline', 'Caroline'), ('Mike', 'Mike'), ('Suzy', 'Suzy'), ('Partners', 'Partners')], default='Default', max_length=254),
        ),
    ]
