# Generated by Django 3.1.2 on 2020-10-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pot',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='team',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='media/images/default_1.png', upload_to='media/profiles'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
